package com.snapbizz.common.config.models

import androidx.room.ColumnInfo
import java.util.Date

//data class ProductInfo(
//    var productCode: Long?,
//    var name: String?,
//    var mrp: Long?,
//    var uom: String?,
//    val vatRate: Double?,
//    val categoryId: Int?,
//    var categoryName: String?,
//    var parentCategoryName: String?,
//    val image: String?,
//    val isGdb: Boolean?,
//    val isDeleted: Boolean?,
//    val createdAt: Date?,
//    val updatedAt: Date?,
//    val hsnCode: String?,
//    val sgstRate: Double?,
//    val cgstRate: Double?,
//    val igstRate: Double?,
//    val cessRate: Double?,
//    val additionalCessRate: Double?,
//    val barcode: Long?,
//    val isSnapOrderSync: Boolean?,
//    val isSyncPending: Boolean?,
//    val isExclusiveGst: Boolean?,
//    val packSize: Int?,
//    val salePrice1: Long?,
//    val salePrice2: Long?,
//    val salePrice3: Long?,
//    var purchasePrice: Long?,
//    val isDefault: Boolean?,
//    val packBarcode: Long?,
//    val expDate: Date?,
//    var inventoryQuantity: Long?,
//    val minimumBaseQuantity: Long?,
//    val reOrderPoint: Long?,
//    val isQuickAdd: Boolean?
//)

data class ProductInfo(
    @ColumnInfo(name = "productCode") val productCode: String,
    @ColumnInfo(name = "name") val name: String,
    @ColumnInfo(name = "mrp") val mrp: Double,
    @ColumnInfo(name = "uom") val uom: String,
    @ColumnInfo(name = "vatRate") val vatRate: Double,
    @ColumnInfo(name = "categoryId") val categoryId: Int,
    @ColumnInfo(name = "image") val image: String,
    @ColumnInfo(name = "isGdb") val isGdb: Int,
    @ColumnInfo(name = "isDeleted") val isDeleted: Int,
    @ColumnInfo(name = "createdAt") val createdAt: String?,
    @ColumnInfo(name = "updatedAt") val updatedAt: String?,
    @ColumnInfo(name = "hsnCode") val hsnCode: String,
    @ColumnInfo(name = "sgstRate") val sgstRate: Double,
    @ColumnInfo(name = "cgstRate") val cgstRate: Double,
    @ColumnInfo(name = "igstRate") val igstRate: Double,
    @ColumnInfo(name = "cessRate") val cessRate: Double,
    @ColumnInfo(name = "additionalCessRate") val additionalCessRate: Double,
    @ColumnInfo(name = "barcode") val barcode: Long,
    @ColumnInfo(name = "isSnapOrderSync") val isSnapOrderSync: Int,
    @ColumnInfo(name = "isSyncPending") val isSyncPending: Int,
    @ColumnInfo(name = "isExclusiveGst") val isExclusiveGst: Int,
    @ColumnInfo(name = "packSize") val packSize: Int,
    @ColumnInfo(name = "salePrice1") val salePrice1: Double,
    @ColumnInfo(name = "salePrice2") val salePrice2: Double,
    @ColumnInfo(name = "salePrice3") val salePrice3: Double,
    @ColumnInfo(name = "purchasePrice") val purchasePrice: Double,
    @ColumnInfo(name = "isDefault") val isDefault: Int,
    @ColumnInfo(name = "packBarcode") val packBarcode: Long,
    @ColumnInfo(name = "expDate") val expDate: String?,
    @ColumnInfo(name = "inventoryQuantity") val inventoryQuantity: Int,
    @ColumnInfo(name = "minimumBaseQuantity") val minimumBaseQuantity: Int,
    @ColumnInfo(name = "reOrderPoint") val reOrderPoint: Int
)