package com.snapbizz.common.models

import androidx.room.ColumnInfo

//data class ProductInfo(
//    var productCode: Long?,
//    var name: String?,
//    var mrp: Long?,
//    var uom: String?,
//    val vatRate: Double?,
//    val categoryId: Int?,
//    val image: String?,
//    val isGdb: Boolean?,
//    val isDeleted: Boolean?,
//    val createdAt: Date?,
//    val updatedAt: Date?,
//    val hsnCode: String?,
//    val sgstRate: Double?,
//    val cgstRate: Double?,
//    val igstRate: Double?,
//    val cessRate: Double?,
//    val additionalCessRate: Double?,
//    val barcode: Long?,
//    val isSnapOrderSync: Boolean?,
//    val isSyncPending: Boolean?,
//    val isExclusiveGst: Boolean?,
//    val packSize: Int?,
//    val salePrice1: Long?,
//    val salePrice2: Long?,
//    val salePrice3: Long?,
//    var purchasePrice: Long?,
//    val isDefault: Boolean?,
//    val packBarcode: Long?,
//    val expDate: Date?,
//    var inventoryQuantity: Long?,
//    val minimumBaseQuantity: Long?,
//    val reOrderPoint: Long?,
//    val isQuickAdd: Boolean?
//)

data class ProductInfo(
    @ColumnInfo(name = "productCode") var productCode: String? = null,
    @ColumnInfo(name = "name") var name: String? = null,
    @ColumnInfo(name = "mrp") var mrp: Double? = null,
    @ColumnInfo(name = "uom") var uom: String? = null,
    @ColumnInfo(name = "vatRate") val vatRate: Double? = null,
    @ColumnInfo(name = "categoryId") val categoryId: Int? = null,
    @ColumnInfo(name = "image") val image: String? = null,
    @ColumnInfo(name = "isGdb") val isGdb: Int? = null,
    @ColumnInfo(name = "isDeleted") val isDeleted: Int? = null,
    @ColumnInfo(name = "createdAt") val createdAt: String? = null,
    @ColumnInfo(name = "updatedAt") val updatedAt: String? = null,
    @ColumnInfo(name = "hsnCode") val hsnCode: String? = null,
    @ColumnInfo(name = "sgstRate") val sgstRate: Double? = null,
    @ColumnInfo(name = "cgstRate") val cgstRate: Double? = null,
    @ColumnInfo(name = "igstRate") val igstRate: Double? = null,
    @ColumnInfo(name = "cessRate") val cessRate: Double? = null,
    @ColumnInfo(name = "additionalCessRate") val additionalCessRate: Double? = null,
    @ColumnInfo(name = "barcode") val barcode: Long? = null,
    @ColumnInfo(name = "isSnapOrderSync") val isSnapOrderSync: Int? = null,
    @ColumnInfo(name = "isSyncPending") val isSyncPending: Int? = null,
    @ColumnInfo(name = "isExclusiveGst") val isExclusiveGst: Int? = null,
    @ColumnInfo(name = "packSize") val packSize: Int? = null,
    @ColumnInfo(name = "salePrice1") val salePrice1: Double? = null,
    @ColumnInfo(name = "salePrice2") val salePrice2: Double? = null,
    @ColumnInfo(name = "salePrice3") val salePrice3: Double? = null,
    @ColumnInfo(name = "purchasePrice") var purchasePrice: Double? = null,
    @ColumnInfo(name = "isDefault") val isDefault: Int? = null,
    @ColumnInfo(name = "packBarcode") val packBarcode: Long? = null,
    @ColumnInfo(name = "expDate") val expDate: String? = null,
    @ColumnInfo(name = "inventoryQuantity") var inventoryQuantity: Int? = null,
    @ColumnInfo(name = "minimumBaseQuantity") val minimumBaseQuantity: Int? = null,
    @ColumnInfo(name = "reOrderPoint") val reOrderPoint: Int? = null
)
